version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraft-vanilla-data:/data
      - /root/minecraft/minecraft-servers/vanilla/plugins:/plugins
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      VERSION: "1.20.0"
    tty: true
    stdin_open: true
    restart: unless-stopped
volumes:
  minecraft-vanilla-data:
    external: true
